// <auto-generated />
using System;
using HeyChefe.Infra.Data.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeyChefe.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809021730_CampoDataHoraRegistro")]
    partial class CampoDataHoraRegistro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeyChefe.Domain.Entidades.Categorias.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraRegistro")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tb_categorias", (string)null);
                });

            modelBuilder.Entity("HeyChefe.Domain.Entidades.Itens.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Situacao")
                        .HasColumnType("int")
                        .HasComment("Situação do usuário: 0-Ativo | 1-Inativo | 2-Excluído |3-Sem Estoque");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("tb_itens", (string)null);
                });

            modelBuilder.Entity("HeyChefe.Domain.Entidades.Mesas.Mesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Situacao")
                        .HasColumnType("int")
                        .HasComment("Situação do usuário: 0-Disponivel | 1-Ocupada | 2-LimpezaPendente |3-Reservada");

                    b.HasKey("Id");

                    b.ToTable("tb_mesa", (string)null);
                });

            modelBuilder.Entity("HeyChefe.Domain.Entidades.Pedidos.LinhaPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Cortesia")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraRegistro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("Situacao")
                        .HasColumnType("int")
                        .HasComment("Situação do usuário: 0-Pendente | 1-Pronto | 2-Concluido |3-Cancelado");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PedidoId");

                    b.ToTable("tb_linhas_pedidos", (string)null);
                });

            modelBuilder.Entity("HeyChefe.Domain.Entidades.Pedidos.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fechamento")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MesaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int")
                        .HasColumnName("Prioridade");

                    b.Property<int>("Situacao")
                        .HasColumnType("int")
                        .HasComment("Situação do usuário: 0-Pendente | 1-Iniciado | 2-Concluido |3-Cancelado");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MesaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tb_pedidos", (string)null);
                });

            modelBuilder.Entity("HeyChefe.Domain.Entidades.Segurança.Autenticacao", b =>
                {
                    b.Property<string>("IdSession")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("ExpirationRefresh")
                        .HasColumnType("bigint");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Revoke")
                        .HasColumnType("bit");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdSession");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Autenticacao");
                });

            modelBuilder.Entity("HeyChefe.Domain.Entidades.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Permissao")
                        .HasColumnType("int")
                        .HasComment("Permissões do usuário: 0-Administrador | 1-Garçom | 2-Cozinha");

                    b.Property<int>("Situacao")
                        .HasColumnType("int")
                        .HasComment("Situação do usuário: 0-Ativo | 1-Inativo");

                    b.HasKey("Id");

                    b.ToTable("tb_usuarios", (string)null);
                });

            modelBuilder.Entity("HeyChefe.Domain.Entidades.Categorias.Categoria", b =>
                {
                    b.OwnsOne("HeyChefe.Domain.Objetos_de_Valor.Codigo", "Codigo", b1 =>
                        {
                            b1.Property<Guid>("CategoriaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Valor")
                                .HasColumnType("int")
                                .HasColumnName("Codigo");

                            b1.HasKey("CategoriaId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("tb_categorias");

                            b1.WithOwner()
                                .HasForeignKey("CategoriaId");
                        });

                    b.OwnsOne("HeyChefe.Domain.Objetos_de_Valor.Cor", "Cor", b1 =>
                        {
                            b1.Property<Guid>("CategoriaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Cor");

                            b1.HasKey("CategoriaId");

                            b1.ToTable("tb_categorias");

                            b1.WithOwner()
                                .HasForeignKey("CategoriaId");
                        });

                    b.OwnsOne("HeyChefe.Domain.Objetos_de_Valor.Titulo.TituloCategoria", "Titulo", b1 =>
                        {
                            b1.Property<Guid>("CategoriaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("Titulo");

                            b1.HasKey("CategoriaId");

                            b1.ToTable("tb_categorias");

                            b1.WithOwner()
                                .HasForeignKey("CategoriaId");
                        });

                    b.Navigation("Codigo")
                        .IsRequired();

                    b.Navigation("Cor")
                        .IsRequired();

                    b.Navigation("Titulo")
                        .IsRequired();
                });

            modelBuilder.Entity("HeyChefe.Domain.Entidades.Itens.Item", b =>
                {
                    b.HasOne("HeyChefe.Domain.Entidades.Categorias.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("HeyChefe.Domain.Objetos_de_Valor.Codigo", "Codigo", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Valor")
                                .HasColumnType("int")
                                .HasColumnName("Codigo");

                            b1.HasKey("ItemId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("tb_itens");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.OwnsOne("HeyChefe.Domain.Objetos_de_Valor.Saldo", "MargemLucro", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("MargemLucro");

                            b1.HasKey("ItemId");

                            b1.ToTable("tb_itens");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.OwnsOne("HeyChefe.Domain.Objetos_de_Valor.Saldo", "PrecoVenda", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PrecoVenda");

                            b1.HasKey("ItemId");

                            b1.ToTable("tb_itens");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.OwnsOne("HeyChefe.Domain.Objetos_de_Valor.Observação.ObservacaoItem", "Descricao", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)")
                                .HasColumnName("Descricao");

                            b1.HasKey("ItemId");

                            b1.ToTable("tb_itens");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.OwnsOne("HeyChefe.Domain.Objetos_de_Valor.Titulo.TituloItem", "Nome", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("Nome");

                            b1.HasKey("ItemId");

                            b1.ToTable("tb_itens");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("Categoria");

                    b.Navigation("Codigo")
                        .IsRequired();

                    b.Navigation("Descricao");

                    b.Navigation("MargemLucro")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("PrecoVenda")
                        .IsRequired();
                });

            modelBuilder.Entity("HeyChefe.Domain.Entidades.Mesas.Mesa", b =>
                {
                    b.OwnsOne("HeyChefe.Domain.Objetos_de_Valor.Codigo", "Codigo", b1 =>
                        {
                            b1.Property<Guid>("MesaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Valor")
                                .HasColumnType("int")
                                .HasColumnName("Codigo");

                            b1.HasKey("MesaId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("tb_mesa");

                            b1.WithOwner()
                                .HasForeignKey("MesaId");
                        });

                    b.Navigation("Codigo")
                        .IsRequired();
                });

            modelBuilder.Entity("HeyChefe.Domain.Entidades.Pedidos.LinhaPedido", b =>
                {
                    b.HasOne("HeyChefe.Domain.Entidades.Itens.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeyChefe.Domain.Entidades.Pedidos.Pedido", null)
                        .WithMany("LinhasPedido")
                        .HasForeignKey("PedidoId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("HeyChefe.Domain.Entidades.Pedidos.Pedido", b =>
                {
                    b.HasOne("HeyChefe.Domain.Entidades.Mesas.Mesa", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("MesaId");

                    b.HasOne("HeyChefe.Domain.Entidades.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("HeyChefe.Domain.Objetos_de_Valor.Codigo", "NumeroPedido", b1 =>
                        {
                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Valor")
                                .HasColumnType("int")
                                .HasColumnName("NumeroPedido");

                            b1.HasKey("PedidoId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("tb_pedidos");

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");
                        });

                    b.Navigation("NumeroPedido")
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HeyChefe.Domain.Entidades.Segurança.Autenticacao", b =>
                {
                    b.HasOne("HeyChefe.Domain.Entidades.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HeyChefe.Domain.Entidades.Usuarios.Usuario", b =>
                {
                    b.OwnsOne("HeyChefe.Domain.Objetos_de_Valor.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("tb_usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("HeyChefe.Domain.Objetos_de_Valor.NomeUsuario", "Nome", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Primeiro")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("PrimeiroNome");

                            b1.Property<string>("Segundo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("SegundoNome");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("tb_usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("HeyChefe.Domain.Objetos_de_Valor.Senha", "Senha", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Senha");

                            b1.Property<string>("Salt")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Salt");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("tb_usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("Senha")
                        .IsRequired();
                });

            modelBuilder.Entity("HeyChefe.Domain.Entidades.Mesas.Mesa", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("HeyChefe.Domain.Entidades.Pedidos.Pedido", b =>
                {
                    b.Navigation("LinhasPedido");
                });
#pragma warning restore 612, 618
        }
    }
}
