<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HeyChefe.Domain\HeyChefe.Domain.csproj" />
    <ProjectReference Include="..\HeyChefe.Infra.Data\HeyChefe.Infra.Data.csproj" />
  </ItemGroup>

</Project>
